# Generated by Django 5.2.1 on 2025-06-07 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Evento')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Evento')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade (kg, L, un)')),
                ('tipo', models.CharField(choices=[('CARNE', 'Carne'), ('BEBIDA', 'Bebida'), ('SUPRIMENTO', 'Suprimento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo do Item')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='churras.evento')),
            ],
        ),
    ]
