# Generated by Django 5.2.1 on 2025-06-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_evento_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('CARNE', 'Carne'), ('BEBIDA', 'Bebida'), ('SUPRIMENTO', 'Suprimento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(default='kg', max_length=10),
        ),
    ]
