# Generated by Django 5.2.3 on 2025-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome_funcionario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email_funcionario')),
            ],
        ),
    ]
