from classe import Produto
notebook = Produto('Notebook Dell i7', 5800.90)
input('Pressione qualquer tecla para ver as ofertas: ')
notebook.verProduto()
print(' ')
iphone = Produto('Iphone 16', 15000.95)
input('Pressione qualquer tecla para ver as ofertas: ')
iphone.verProduto()
print(' ')
varProduto = input('Informe o produto: ')
print(' ')
varPreco = float(input('Informe o preço: '))
print(' ')
produtoDoUsuario = Produto(varProduto, varPreco)
produtoDoUsuario.verProduto()
print()