# Generated by Django 5.2.3 on 2025-06-28 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_alter_prato_tempo_preparo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='date_prato',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='prato',
            name='modo_preparo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(max_length=100),
        ),
    ]
